# Generated by Django 4.2.16 on 2025-09-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ochiq parol'),
        ),
    ]
