# Generated by Django 4.2.16 on 2025-09-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zona nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yetkazib berish haqi')),
                ('delivery_time', models.PositiveIntegerField(default=30, verbose_name='Yetkazib berish vaqti (daqiqa)')),
                ('working_hours_start', models.TimeField(default='09:00', verbose_name='Ish boshlanish vaqti')),
                ('working_hours_end', models.TimeField(default='23:00', verbose_name='Ish tugash vaqti')),
                ('is_24_hours', models.BooleanField(default=False, verbose_name='24 soat ishlaydi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Yetkazib berish zonasi',
                'verbose_name_plural': 'Yetkazib berish zonalari',
            },
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yotoqxona nomi')),
                ('address', models.TextField(verbose_name="To'liq manzil")),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name="Mas'ul shaxs")),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqam')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Uzunlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.deliveryzone', verbose_name='Yetkazib berish zonasi')),
            ],
            options={
                'verbose_name': 'Yotoqxona',
                'verbose_name_plural': 'Yotoqxonalar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('preparing', 'Tayyorlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('completed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('online', "Online to'lov")], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('delivery_address', models.TextField(verbose_name='Yetkazib berish manzili')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Xona raqami')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazib berish vaqti')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy summa')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yetkazib berish haqi')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.deliveryzone', verbose_name='Yetkazib berish zonasi')),
                ('dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.dormitory', verbose_name='Yotoqxona')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiya')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="To'liq ism")),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yosh')),
                ('room_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Xona raqami')),
                ('is_registered', models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tgan")),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.dormitory', verbose_name='Yotoqxona')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='OrderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(verbose_name='Yetkazib berish manzili')),
                ('room_number', models.CharField(max_length=20, verbose_name='Xona raqami')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('additional_notes', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugatilgan')),
                ('dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.dormitory', verbose_name='Yotoqxona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma sessiyasi',
                'verbose_name_plural': 'Buyurtma sessiyalari',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Xabar matni')),
                ('message_type', models.CharField(default='text', max_length=50, verbose_name='Xabar turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savatcha',
                'verbose_name_plural': 'Savatchalar',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
