# Generated by Django 4.2 on 2025-09-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zona nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yetkazib berish haqi')),
                ('delivery_time', models.PositiveIntegerField(default=30, verbose_name='Yetkazib berish vaqti (daqiqa)')),
                ('working_hours_start', models.TimeField(default='09:00', verbose_name='Ish boshlanish vaqti')),
                ('working_hours_end', models.TimeField(default='23:00', verbose_name='Ish tugash vaqti')),
                ('is_24_hours', models.BooleanField(default=False, verbose_name='24 soat ishlaydi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Yetkazib berish zonasi',
                'verbose_name_plural': 'Yetkazib berish zonalari',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yetkazib berish vaqti'),
        ),
        migrations.AddField(
            model_name='order',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Xona raqami'),
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yotoqxona nomi')),
                ('address', models.TextField(verbose_name="To'liq manzil")),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name="Mas'ul shaxs")),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqam')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Uzunlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.deliveryzone', verbose_name='Yetkazib berish zonasi')),
            ],
            options={
                'verbose_name': 'Yotoqxona',
                'verbose_name_plural': 'Yotoqxonalar',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.deliveryzone', verbose_name='Yetkazib berish zonasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.dormitory', verbose_name='Yotoqxona'),
        ),
    ]
