# Generated by Django 4.2.16 on 2025-09-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Xona raqami'),
        ),
        migrations.AlterField(
            model_name='ordersession',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Xona raqami'),
        ),
    ]
