# Generated by Django 4.2.16 on 2025-09-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_order_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_zone',
        ),
        migrations.AddField(
            model_name='dormitory',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yetkazib berish haqi'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='delivery_time',
            field=models.PositiveIntegerField(default=30, verbose_name='Yetkazib berish vaqti (daqiqa)'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='is_24_hours',
            field=models.BooleanField(default=False, verbose_name='24 soat ishlaydi'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='working_hours_end',
            field=models.TimeField(default='23:00', verbose_name='Ish tugash vaqti'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='working_hours_start',
            field=models.TimeField(default='09:00', verbose_name='Ish boshlanish vaqti'),
        ),
    ]
