# Generated by Django 4.2 on 2025-09-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_deliveryzone_order_delivery_time_order_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Yosh'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.dormitory', verbose_name='Yotoqxona'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tgan"),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tgan sana"),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Xona raqami'),
        ),
    ]
