# Generated by Django 4.2 on 2025-09-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramuser_age_telegramuser_dormitory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(verbose_name='Yetkazib berish manzili')),
                ('room_number', models.CharField(max_length=20, verbose_name='Xona raqami')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('additional_notes', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugatilgan')),
                ('dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.dormitory', verbose_name='Yotoqxona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma sessiyasi',
                'verbose_name_plural': 'Buyurtma sessiyalari',
            },
        ),
    ]
