# Generated by Django 4.2.16 on 2025-09-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_remove_courierstaff_delivery_zones'),
        ('bot', '0004_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryZone',
        ),
    ]
