# Generated by Django 4.2.16 on 2025-09-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('position', models.CharField(default='Oshpaz', max_length=100, verbose_name='Lavozim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Oshxona xodimi',
                'verbose_name_plural': 'Oshxona xodimlari',
            },
        ),
        migrations.CreateModel(
            name='OrderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Qabul qilindi'), ('preparing', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('picked_up', 'Kuryer oldi'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='received', max_length=20, verbose_name='Holat')),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tayyorlash vaqti (daqiqa)')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlandi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugadi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilandi')),
                ('kitchen_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.kitchenstaff', verbose_name='Oshxona xodimi')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma holati',
                'verbose_name_plural': 'Buyurtma holatlari',
            },
        ),
    ]
