# Generated by Django 4.2.16 on 2025-09-13 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Foydalanuvchi'),
        ),
    ]
