# Generated by Django 4.2.16 on 2025-09-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('vehicle_type', models.CharField(default='Piyoda', max_length=50, verbose_name='Transport turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('delivery_zones', models.ManyToManyField(blank=True, to='bot.deliveryzone', verbose_name='Yetkazib berish zonalari')),
            ],
            options={
                'verbose_name': 'Kuryer',
                'verbose_name_plural': 'Kuryerlar',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'Tayyor'), ('assigned', 'Tayinlandi'), ('picked_up', 'Olib ketildi'), ('on_way', "Yo'lda"), ('delivered', 'Yetkazildi'), ('failed', 'Muvaffaqiyatsiz'), ('returned', 'Qaytarildi')], default='ready', max_length=20, verbose_name='Holat')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Tayinlangan vaqt')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Olingan vaqt')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan vaqt')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Yetkazib berish manzili')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Yetkazib berish izohlari')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='Mijoz fikri')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baho (1-5)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilandi')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier.courierstaff', verbose_name='Kuryer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Yetkazib berish',
                'verbose_name_plural': 'Yetkazib berishlar',
            },
        ),
    ]
