# Generated by Django 4.2 on 2025-09-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_time',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='pickup_time',
            new_name='picked_up_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tayinlangan vaqt'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Yetkazib berish manzili'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('ready', 'Tayyor'), ('assigned', 'Tayinlandi'), ('picked_up', 'Olib ketildi'), ('on_way', "Yo'lda"), ('delivered', 'Yetkazildi'), ('failed', 'Muvaffaqiyatsiz'), ('returned', 'Qaytarildi')], default='ready', max_length=20, verbose_name='Holat'),
        ),
    ]
