# Generated by Django 4.2.16 on 2025-09-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_alter_courierstaff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierstaff',
            name='delivery_zones',
        ),
    ]
